ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('dj-admin/', admin.site.urls),
    path('admin/', include('customadmin.urls')),
    path('', include('store.urls')),
   
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/store/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.home, name = 'home'),
    path('shop/', views.store, name = 'shop'),
    path('category/<str:categoryname>/', views.categoryView, name = 'categoryview'),
    path('shop/shop-details/<int:id>/', views.shop_details, name = 'shop-details'),
    path('shop/shop-details/<int:id>/size-change/', views.size_change, name = 'size-change'),

    path('shop/search/', views.search_results, name = 'search-results'),
    path('shop/cart/', views.cart, name = 'cart'),

    path('blog/', views.blog, name = 'blog'),
    path('contact/', views.contact, name = 'contact'),
    path('about/', views.about, name = 'about'),
    path('signout/', views.signout, name = 'signout'),
    path('signin/', views.signin, name = 'signin'),
    path('signup/', views.signup, name = 'signup'),
    path('otplogin/', views.otplogin, name = 'otplogin'),
    path('otp/', views.otp, name = 'otp'),
    path('shop/checkout/', views.checkout, name = 'checkout'),
    path('update_item/', views.updateItem, name = 'update_item'),
    path('add_address/', views.addshippingAddress, name = 'add_address'),
    path('process_order/', views.processOrder, name = 'process_order'),
    path('add_coupon/', views.addCoupon, name='add_coupon'),
    path('account/', views.profile, name = 'account'),
    path('orders/', views.myOrders, name = 'orders'),
     path('cancel_order/', views.cancelOrder, name = 'cancel-order'),
    
    path('wishlist/', views.wishlist, name = 'wishlist'),
    path('add_to_wishlist/', views.addToWishlist, name = 'add_to_wishlist'), 
    path('delete_from_wishlist/', views.deleteFromWishlist, name = 'delete_from_wishlist'), 
   
    path('view_invoice/<int:order_id>', views.view_invoice, name = 'view_invoice'),
    
    path('coupons/', views.coupons, name = 'coupons'),

    path('order-complete/', views.order_complete, name = 'order_complete')


    
]

ecommerce/store/models.py
import decimal
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.


class User(AbstractUser):
    phone_number = models.CharField(max_length = 13, unique=True, null=True, blank=True,)
    device = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return str(self.id)




class Offer(models.Model):
    discount = models.IntegerField(default=0, null=True, blank=True)
    valid_from = models.DateTimeField(null=True, blank=True)
    valid_to = models.DateTimeField(null=True, blank=True)
    is_active = models.BooleanField(default=False)

   

class Category(models.Model):
    category_name=models.CharField(max_length=50)
    image= models.ImageField(upload_to="images",default="")
    offer = models.ForeignKey(Offer,on_delete=models.SET_NULL, null=True, blank=True)
    


    def __str__(self):
        return self.category_name

class ColorVariant(models.Model):
    color_name = models.CharField(max_length=100, default='Black')
    color_code = models.CharField(max_length=50, null=True, blank=True)
    price = models.DecimalField(max_digits=7, decimal_places=2, null=True, blank=True, default=0)

    def __str__(self):
        return str(self.color_name)

class SizeVariant(models.Model):
    size_name = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=7, decimal_places=2, null=True, blank=True, default=0)

    def __str__(self):
        return str(self.size_name)

class Products(models.Model):
    name = models.CharField(max_length=200, null=True)
    price = models.DecimalField(max_digits=7, decimal_places=2, null=True, blank=True)
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    quantity = models.IntegerField(null=True, blank=True)
    stock = models.IntegerField(null=True, blank=True)
    description = models.TextField()

    image= models.ImageField( null=True, blank=True)
    image1= models.ImageField( null=True, blank=True)
    image2= models.ImageField( null=True, blank=True)
    image3= models.ImageField( null=True, blank=True)
    trending = models.BooleanField(default=False, help_text="0=default, 1=Trending")
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    offer = models.ForeignKey(Offer,on_delete=models.SET_NULL, null=True, blank=True)
    color_variant = models.ManyToManyField(ColorVariant, blank=True )
    size_variant = models.ManyToManyField(SizeVariant, blank=True )
    

   


    def __str__(self):
        return str(self.name)
        
    @property
    def offerPrice(self):
        offerPrice_decimal = self.price - (self.price * decimal.Decimal(self.offer.discount) * decimal.Decimal(0.01))
        offerPrice = int(offerPrice_decimal)
        return offerPrice
            
    def get_product_price_by_size(self, size):
        if self.offer:
            return self.offerPrice + SizeVariant.objects.get(size_name=size).price
        else:
            return self.price + SizeVariant.objects.get(size_name=size).price

    
           
    
    
    @property
    def imageURL(self):
        try:
            url =self.image.url
        except:
            url=''
        return url

    @property
    def image1URL(self):
        try:
            url =self.image1.url
        except:
            url=''
        return url

    @property
    def image2URL(self):
        try:
            url =self.image2.url
        except:
            url=''
        return url

    @property
    def image3URL(self):
        try:
            url =self.image3.url
        except:
            url=''
        return url




class ShippingAddress(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    name = models.CharField(max_length=50, null=True)
    phone = models.CharField(max_length = 13, null=True, blank=True,)
    address = models.CharField(max_length=200, null=True)
    city = models.CharField(max_length=200, null=True)
    state = models.CharField(max_length=200, null=True)
    zipcode = models.CharField(max_length=200, null=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.id)


 
class Order(models.Model):
    STATUS = (
			('Pending', 'Pending'),
            ('Confirmed', 'Confirmed'),
            ('Shipped', 'Shipped'),
			('Out for delivery', 'Out for delivery'),
			('Delivered', 'Delivered'),
            ('Cancelled', 'Cancelled'),
			)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    shippingaddress = models.ForeignKey(ShippingAddress, on_delete=models.SET_NULL, null=True)
    date_ordered = models.DateTimeField(auto_now_add=True, null=True)
    complete = models.BooleanField(default=False, help_text="0=default, 1=Trending")
    transaction_id = models.CharField(max_length=100, null=True)
    status = models.CharField(max_length=200, null=True, choices=STATUS)
    

    def __str__(self):
        return str(self.id)


    @property
    def get_cart_total(self):
        try:
            orderitems = self.orderitem_set.all()
            total = sum([item.get_total for item in orderitems])
        
            return total
        except:
            pass
       

    @property
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        try:
            total = sum([item.quantity for item in orderitems])
        
            return total

        except:
            pass



class OrderItem(models.Model):
    product = models.ForeignKey(Products, on_delete=models.SET_NULL, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
    quantity = models.IntegerField(default=0,null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)
    color_variant = models.ForeignKey(ColorVariant, on_delete=models.SET_NULL, null=True, blank=True)
    size_variant = models.ForeignKey(SizeVariant, on_delete=models.SET_NULL, null=True, blank=True)

    @property
    def updated_price_by_size(self):
        if self.product.offer:
            return self.product.offerPrice + SizeVariant.objects.get(size_name=self.size_variant).price
        else:
            return self.product.price + SizeVariant.objects.get(size_name=self.size_variant).price

    @property
    def get_total(self):

        if self.product.offer and self.size_variant:
            price = [self.product.offerPrice]
            size_variant_price = self.size_variant.price
            price.append(size_variant_price)
            variant_price = sum(price)
            total = variant_price * self.quantity
            return total

        if self.product.offer:
            total = self.product.offerPrice * self.quantity
            return total
                
        if  self.size_variant:
            price = [self.product.price]
            size_variant_price = self.size_variant.price
            price.append(size_variant_price)
            variant_price = sum(price) 
            total = variant_price * self.quantity
            return total
        else:
            total = self.product.price * self.quantity
            return total

  
    

class Coupons(models.Model):
    couponcode = models.CharField(max_length=200, null=True)
    percent = models.IntegerField(default = 0, null=True, blank=True)
    valid_from = models.DateTimeField(auto_now_add=True)
    valid_to = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)

class Wishlist(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Products, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

ecommerce/store/templates/store/pages/about.html
{% extends 'store/main.html' %}

{% load static %}

{% block content %}
    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-option">
        <div class="container">
            <div class="row"  style="padding-top: 10rem;">
                <div class="col-lg-12">
                    <div class="breadcrumb__text">
                        <h4>About Us</h4>
                        <div class="breadcrumb__links">
                            <a href="./index.html">Home</a>
                            <span>About Us</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->



{% endblock content %}

ecommerce/store/templates/store/pages/category_view.html
{% extends 'store/main.html' %}

{% load static %}

{% block content %}

<!-- Breadcrumb Section Begin -->
<section class="breadcrumb-option">
    <div class="container">
        <div class="row" style="padding-top: 10rem;">
            <div class="col-lg-12">
                <div class="breadcrumb__text">
                    <h4>Shop</h4>
                    <div class="breadcrumb__links">
                        <a href="{% url 'home' %}">Home</a>
                        <a href="{% url 'shop' %}">Shop</a>
                        <span>{{categoryname}}</span>
                    </div>
                    
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Breadcrumb Section End -->

<!-- Shop Section Begin -->
<section class="shop spad">
    <div class="container">
        <div class="row">

            {% include 'store/pages/sidepanel.html' %}

            <div class="col-lg-9">
                <div class="shop__product__option">
                    <div class="row">
                        <div class="col-lg-6 col-md-6 col-sm-6">
                            <div class="shop__product__option__left">
                                <p>Showing 1–12 of 126 results</p>
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-6">
                            <div class="shop__product__option__right">
                                <p>Sort by Price:</p>
                                <select>
                                    <option value="">Low To High</option>
                                    <option value="">$0 - $55</option>
                                    <option value="">$55 - $100</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    {% for product in products %}
                    <div class="col-lg-4 col-md-6 col-sm-6">
                        
                        <div class="product__item">
                            
                            <div class="product__item__pic set-bg " data-setbg="{{product.imageURL}}">
                                <ul class="product__hover">
                                    <li><a href="#"><img src="{% static 'images/icon/heart.png' %}" alt=""><span>Wishlist</span></a></li>
                                    <li><a href="#"><img src="{% static 'images/icon/compare.png' %}" alt=""> <span>Compare</span></a>
                                    </li>
                                    <li><a href="{% url 'shop-details' product.id %}"><img src="{% static 'images/icon/search.png' %}" alt=""></a></li>
                                </ul>
                            </div>
                            <div class="product__item__text">
                                
                                <h6>{{product.name}}</h6>
                                {% csrf_token %}
                                <a data-product = {{product.id}} data-action="add" class="update-cart">+ Add To Cart</a>
                                <div class="rating">
                                    <i class="fa fa-star-o"></i>
                                    <i class="fa fa-star-o"></i>
                                    <i class="fa fa-star-o"></i>
                                    <i class="fa fa-star-o"></i>
                                    <i class="fa fa-star-o"></i>
                                </div>
                               
                                {% if product.offer  %}
    
                                    <div class="row ">
                                        <h5 class="text-danger col-md-5" style="text-decoration: line-through;"> &#8377; {{ product.price|floatformat:2}} </h5>
                                        <h5 class="text-success "> &#8377; {{product.offerPrice|floatformat:2 }}</h5>
                                    </div>
                              

                                {% else %}
                                    <h5> &#8377; {{product.price|floatformat:2}}</h5>
                                {% endif %}
                                



                                <div class="product__color__select">
                                    <label for="pc-4">
                                        <input type="radio" id="pc-4">
                                    </label>
                                    <label class="active black" for="pc-5">
                                        <input type="radio" id="pc-5">
                                    </label>
                                    <label class="grey" for="pc-6">
                                        <input type="radio" id="pc-6">
                                    </label>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
           
                </div>         
                <div class="row">
                    <div class="col-lg-12">
                        <div class="product__pagination">
                            <a class="active" href="#">1</a>
                            <a href="#">2</a>
                            <a href="#">3</a>
                            <span>...</span>
                            <a href="#">21</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


<!-- Shop Section End -->

{% endblock content %}

ecommerce/store/templates/store/pages/coupons.html
{% extends 'store/main.html' %}

{% load static %}

{% block content %}

    
<div class="row" style="padding-top:10rem;">
    <div class="col-lg-6">
        <div class="box-element" id="form-wrapper">
           <h1>Coupons</h1>

        </div>
        <br>
       
    </div> 

  
</div>

{% endblock content %}

ecommerce/store/templates/store/pages/invoice.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Invoice</title>
        <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->
</head>
<body>
	<style>
		.invoice-title h2, .invoice-title h3 {
			display: inline-block;
		}
		
		.table > tbody > tr > .no-line {
			border-top: none;
		}
		
		.table > thead > tr > .no-line {
			border-bottom: none;
		}
		
		.table > tbody > tr > .thick-line {
			border-top: 2px solid;
		}
	</style>
    


<div class="container">
    <div class="row">
        <div class="col-xs-12">
    		<div class="invoice-title">
    			<h2>Invoice</h2><h3 class="pull-right"></h3>
    		</div>
    		<hr>
    		<div class="row" style="margin-top:30px;">
    			<div class="col-xs-6" >
    				<address>
    				<strong>Billed To:</strong><br>
    					{{user.first_name}}<br>
    					{{user.email}}<br>
    					{{user.phone_number}}<br>
    				</address>
    			</div>
    			<div class="col-xs-6 text-right" >
    				<address>
                       
        			<strong>Shipped To:</strong><br>
    					{{current_order.shippingaddress.name}}<br>
    					{{current_order.shippingaddress.address}}<br>
    					{{current_order.shippingaddress.city}}<br>
    					{{current_order.shippingaddress.state}}<br>
    					Pincode : {{current_order.shippingaddress.zipcode}}
    				</address>
                    
    			</div>
    		</div>
            <div class="row" style="margin-top:30px;">
    			<!-- <div class="col-xs-6">
    				<address>
    					<strong>Payment Method:</strong><br>
    					{{oldcart.order.method}}
    				</address>
    			</div> -->
    			<div class="col-xs-6 text-right">
    				<address>
    					<strong>Ordered On:</strong><br>
                        {{current_order.date_ordered}}
                        <br><br>
    				</address>
    			</div>
    		</div>
    		
    	</div>
    </div>
    
    <div class="row">
    	<div class="col-md-12">
    		<div class="panel panel-default">
    			<div class="panel-heading">
    				<h3 class="panel-title"><strong>Order summary</strong></h3>
    			</div>
    			<div class="panel-body">
    				<div class="table-responsive">
    					<table class="table table-condensed">
    						<thead>
                                <tr>
        							<td><strong>Item</strong></td>
        							<td class="text-center"><strong>Price</strong></td>
									<td class="text-center"><strong>Size</strong></td>
        							<td class="text-center"><strong>Quantity</strong></td>
        							<td class="text-right"><strong>Totals</strong></td>
                                </tr>
    						</thead>
    						<tbody>
    							{% for orderitem in orderitems%}
    							<tr>
    								<td>{{orderitem.product.name}}</td>
    								<td class="text-center">{{orderitem.product.price}}</td>
									<td class="text-center">{{orderitem.size_variant}}</td>
    								<td class="text-center">{{orderitem.quantity}}</td>
    								<td class="text-right">{{orderitem.get_total}}</td>
    							</tr>
                                {% endfor %}
                                
                                <tr></tr>
                                <tr></tr>
    							<tr>
    								<td class="thick-line"></td>
    								<td class="thick-line"></td>
    								<td class="thick-line text-center"><strong>Subtotal</strong></td>
    								<td class="thick-line text-right">{{current_order.get_cart_total}}</td>
    							</tr>
                                
    							<tr>
    								<td class="no-line"></td>
    								<td class="no-line"></td>
    								<td class="no-line text-center"><strong>Shipping</strong></td>
    								<td class="no-line text-right">Free</td>
    							</tr>
    							<tr>
    								<td class="no-line"></td>
    								<td class="no-line"></td>
    								<td class="no-line text-center"><strong>Total</strong></td>
    								<td class="no-line text-right">{{current_order.get_cart_total}}</td>
    							</tr>
    						</tbody>
    					</table>
    				</div>
    			</div>
    		</div>
    	</div>
    </div>
</div>
</body>
</html>

ecommerce/store/templates/store/pages/order_complete.html
{% extends 'store/main.html' %}

{% load static %}

{% block content %}

    
<div class="row" style="padding-top:10rem;">
    <div class="col-lg-6 mx-auto">
        <div class="box-element  text-center" id="form-wrapper">
  
                <h3 >Thank You for the Purchase</h3>
                <br>
    
                <a class="btn btn-success" href="{% url 'shop' %}">Return to Shop</a>

           
           
           <a class="btn btn-success" href="{% url 'orders' %}">View Order History</a>

        </div>
        <br>
       
    </div> 

  
</div>

{% endblock content %}

ecommerce/store/templates/store/pages/profile.html
{% extends 'store/main.html' %}

{% load static %}

{% block content %}



<div class="row" style="padding-top:10rem;">

    <div class="container">
        <div class="row">
            <div class="col-md-12 p-4">
                <div class="invoice-title">
                    <h2>Addresses</h2><h3 class="pull-right"></h3>
                </div>
                <hr>
                <div class="row" style="margin-top:30px;">
                    {% for i in shippingaddress %}
                    <div class="col-md-3" >
                        <address>
                        <strong> {{i.name}} </strong><br>
                          Phone : {{i.phone}} <br>
                            {{i.address}} <br>
                            {{i.city}} <br>
                            {{i.state}}, {{i.zipcode}}

                        </address>
                    </div>
                    {% endfor %}
                    
                </div>
             
                
            </div>
        </div>
     
    </div>
  
</div>
{% endblock content %}

ecommerce/store/templates/store/pages/sidepanel.html
<div class="col-lg-3">
    <div class="shop__sidebar">
        <div class="shop__sidebar__search">
            <form id="search-form">
                {% csrf_token %}
                <input type="text" id="search-input" class="search" name="q" placeholder="Search...">
                <button type="reset"><span class="icon_search"></span></button>
                
            </form>
            <div id="results-box" class="results-card d-none"></div>
        </div>
        <div class="shop__sidebar__accordion">
            <div class="accordion" id="accordionExample">
                <div class="card">
                    <div class="card-heading">
                        <a data-toggle="collapse" data-target="#collapseOne">Categories</a>
                    </div>
                    <div id="collapseOne" class="collapse show" data-parent="#accordionExample">
                        <div class="card-body">
                            <div class="shop__sidebar__categories">
                                <ul class="nice-scroll">
                                    {% for category in categories %}
                                        {% if category.offer %}
                                            <li><a class="sidebar_category_links" href="{% url 'categoryview' category.category_name %}">{{category.category_name}} ({{category.products_set.all.count}})</a> <span class="text-success fw-bold">{{category.offer.discount}}% off</span></li>
                                        {% else %}
                                            <li><a class="sidebar_category_links" href="{% url 'categoryview' category.category_name %}">{{category.category_name}} ({{category.products_set.all.count}})</a></li>
                                        {% endif %}
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
          
                <div class="card">
                    <div class="card-heading">
                        <a data-toggle="collapse" data-target="#collapseThree">Filter Price</a>
                    </div>
                    <div id="collapseThree" class="collapse show" data-parent="#accordionExample">
                        <div class="card-body">
                            <div class="shop__sidebar__price">
                                <ul id = "filter-list">
                                    <li><a value="200">&#8377; 200.00 - &#8377; 299.00</a></li>
                                    <li><a value="300">&#8377; 300.00 - &#8377; 399.00</a></li>
                                    <li><a value="400">&#8377; 400.00 - &#8377; 499.00</a></li>
                                    <li><a value="500">&#8377; 500.00 - &#8377; 599.00</a></li>
                                    <li><a value="600">&#8377; 600.00 - &#8377; 699.00</a></li>
                                    <li><a value="700">&#8377; 700 +</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card">
                    <div class="card-heading">
                        <a data-toggle="collapse" data-target="#collapseFour">Size</a>
                    </div>
                    <div id="collapseFour" class="collapse show" data-parent="#accordionExample">
                        <div class="card-body">
                            <div class="shop__sidebar__size">
                                {% for size_variant in size_variant %}
                                <label for="sm">{{size_variant.size_name}}
                                    <input value="{{size.size__id}}" type="radio" id="sm">
                                </label>
                                {% endfor %}
                             
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card">
                    <div class="card-heading">
                        <a data-toggle="collapse" data-target="#collapseFive">Colors</a>
                    </div>
                    <div id="collapseFive" class="collapse show" data-parent="#accordionExample">
                        <div class="card-body">
                            <div class="shop__sidebar__color">
                                {% for color_variant in color_variant %}
                                <label class="c-1" for="sp-1" style="background:{{color_variant.color_code}}">
                                    <input value="" type="radio" id="sp-1">
                                </label>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
           
            </div>
        </div>
    </div>
</div>

<script>

    const f_url = window.location.href
    const searchForm = document.getElementById('search-form')
    const searchInput = document.getElementById('search-input')
    const resultsBox = document.getElementById('results-box')
    const csrf = document.getElementsByName('csrfmiddlewaretoken')[0].value


    const sendSearchData = (item) => {

        $.ajax({
            type: 'POST',
            url: '/shop/search/',
            data:{
                'csrfmiddlewaretoken': csrf,
                'search_products': item
            },
            success: (res) => {
               
                const data = res.data
                console.log(data)

                if (Array.isArray(data)){
                    resultsBox.innerHTML = ""
                    data.forEach( search_products => {
                        resultsBox.innerHTML += `
                            <a href="shop-details/${search_products.pk}" class="search_item"> 
                                <div class="row mt-2 mb-2"> 
                                    <div class="col-4"> 
                                        <img src="${search_products.image}"" class="search-img"> 
                                    </div>
                                    <div class="col-8 my-auto"> 
                                        <h6>${search_products.name}</h6>
                                    </div>
                                </div>
                            </a> 
                        `
                    })
                }else{
                    if (searchInput.value.length > 0){
                        resultsBox.innerHTML = `<b>${data}</b>`
                    } else {
                        resultsBox.classList.add('d-none')
                    }
                }


            },
            error: (err) => {
                console.log(err)
            }

        })

    }



    searchInput.addEventListener('keyup', e => {
        console.log(e.target.value)
        if (resultsBox.classList.contains('d-none')){
            resultsBox.classList.remove('d-none')
        }

        sendSearchData (e.target.value)
    })

    




    // Active link for the selected category
    const currentlocation = location.href
    console.log(location.href)
    const sidelinks = document.getElementsByClassName("sidebar_category_links")
    console.log(sidelinks[0].href)
    for(var i=0; i < sidelinks.length; i++){
        if(sidelinks[i].href === currentlocation){
            
            sidelinks[i].classList.add = "shop__sidebar__brand_active"
        }
    }



    //............Filter using price..............

    // IE does not know about the target attribute. It looks for srcElement
    // This function will get the event target in a browser-compatible way

    function getEventTarget(e) {
        e = e || window.event;
        return e.target || e.srcElement; 
    }



    var filter_list = document.getElementById('filter-list');

    filter_list.onclick = function(event) {
        var target = getEventTarget(event);
        console.log(target.getAttribute("value"))
       
        var url = new URL(window.location.href) 
        var search_params = url.searchParams; 
        search_params.set('price', target.getAttribute("value"))
        url.search = search_params.toString()
        console.log(url.search)
        location = url
        
    };



</script>